import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

var DEFAULT_HEIGHT = "100";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next.js Data Fetching</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          style={{
            display: "flex",
            flexDirection: 'column',
            height: `${DEFAULT_HEIGHT}vh`,
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <h1>Next.js Data Fetching Tutorial by Paul Nathaniel</h1>
          <h4>In this repository - you will learn basic data fetching using Next.js</h4>
          <span>These methods are - Server sider rendering, static site generation, incremental static regeneration on basic react client-side rendering.</span>
          <span>Learn more here in this documentation <a href="https://nextjs.org/docs/basic-features/data-fetching/overview">Data Fetching Overview by Next.js Team.</a></span>
        </div>
      </main>
    </>
  );
}
